---
title: "Reconstruct the single subject"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


+ read data 

```{r}
library(FLGP)
library(kernlab)
library(readxl)
library(ggplot2)
```

```{r}
subject = "100206"
data = read.csv(paste0("G:/Phd/Data/HCPFMRI/2bk-0bk/",subject,"_2bk-0bk.csv"))
X = as.matrix(data[,1:3])
y = data[,4]
code = data[,5]
```

```{r}
aal_region = read_excel("G:/Phd/Data/HCPFMRI/AALregion_full.xls")
```

```{r}
idx = (X[,1]==X[10000,1])
mydata = X[idx,2:3]
meas = y[idx]
ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=meas)) +
  scale_color_gradientn(colours = rainbow(10)) +
  xlab("Y") + ylab("Z") + labs(colour="Measured value")
ggsave(paste0("plots/hcp/slice_0.pdf"))
```

```{r}
idx = (X[,1]==X[20000,1])
mydata = X[idx,2:3]
meas = y[idx]
ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=meas)) +
  scale_color_gradientn(colours = rainbow(10)) +
  xlab("Y") + ylab("Z") + labs(colour="Measured value")
ggsave(paste0("plots/hcp/slice_1.pdf"))
```

```{r}
idx = (X[,1]==X[50000,1])
mydata = X[idx,2:3]
meas = y[idx]
ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=meas)) +
  scale_color_gradientn(colours = rainbow(10)) +
  xlab("Y") + ylab("Z") + labs(colour="Measured value")
ggsave(paste0("plots/hcp/slice_2.pdf"))
```

```{r}
idx = (X[,1]==X[100000,1])
mydata = X[idx,2:3]
meas = y[idx]
ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=meas)) +
  scale_color_gradientn(colours = rainbow(10)) +
  xlab("Y") + ylab("Z") + labs(colour="Measured value")
ggsave(paste0("plots/hcp/slice_3.pdf"))
```
```{r}
act = quantile(abs(y),probs = 0.95)
```


```{r}
set.seed(1234)
```


## Experiment
```{r}
n = nrow(X); nregion = nrow(aal_region)
num_exps = 10 # experiment numbers
ms = c(500,1000,2000,5000,10000,20000) # number of labeled samples
res_list = lapply(c(1:(length(ms)*3)), function(i) {return(matrix(0,nrow=4,ncol=num_exps))})
rbf_res = lapply(c(1:(length(ms)*2)), function(i) {return(matrix(0,nrow=nregion,ncol=num_exps))})
lkflag_res = lapply(c(1:(length(ms)*2)), function(i) {return(matrix(0,nrow=nregion,ncol=num_exps))})
```

```{r}
# hyper parameters
s = 1000; r = 3; K = 200
models = list(subsample="kmeans", kernel="lae", gl="cluster-normalized", root=TRUE)
```

```{r, include=FALSE}
time_start = Sys.time()

for(i in c(1:length(ms))) {

for(num_exp in c(1:num_exps)) {
  

cat("\n\n##########################################################\n")  
cat(paste0("When m = ",ms[i],", the ",num_exp, "-th experiment:\n\n"))
  
# regression
m = ms[i]
train.index = sample.int(n, m)
test.index = c(1:n)[-train.index]
X.train = X[train.index,]; X.test = X[test.index,]
y.train = y[train.index]; y.test = y[test.index]
code.train = code[train.index]; code.test = code[test.index]

# radial basis kernel function
t1 = Sys.time()
rbf.hcp = gausspr(x=X.train, y=y.train)
train_pred.hcp = predict(rbf.hcp, X.train)
test_pred.hcp = predict(rbf.hcp, X.test)
t2 = Sys.time()
mse_train.rbf.hcp = sum((y.train-train_pred.hcp)^2)/m
mse_test.rbf.hcp = sum((y.test-test_pred.hcp)^2)/(n-m)

mse_train_act.rbf.hcp = sum((y.train[abs(y.train)>act]-train_pred.hcp[abs(y.train)>act])^2)/sum(abs(y.train)>act)
mse_test_act.rbf.hcp = sum((y.test[abs(y.test)>act]-test_pred.hcp[abs(y.test)>act])^2)/sum(abs(y.test)>act)

res_list[[3*i-2]][1,num_exp] = mse_train.rbf.hcp
res_list[[3*i-2]][3,num_exp] = mse_train_act.rbf.hcp
res_list[[3*i-1]][1,num_exp] = mse_test.rbf.hcp
res_list[[3*i-1]][3,num_exp] = mse_test_act.rbf.hcp
res_list[[3*i]][1,num_exp] = as.numeric(t2-t1, units="hours")*3600


# LKFLGP
models$subsample = "kmeans"; models$gl = "cluster-normalized"
t1 = Sys.time()
res_lkflag.hcp = fit_lae_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models, noise = "same")
t2 = Sys.time()
y_lkflag.hcp = res_lkflag.hcp$Y_pred
train_pred_lkflag.hcp = y_lkflag.hcp$train
test_pred_lkflag.hcp = y_lkflag.hcp$test

mse_train.lkflag.hcp = sum((y.train-train_pred_lkflag.hcp)^2)/m
mse_test.lkflag.hcp = sum((y.test-test_pred_lkflag.hcp)^2)/(n-m)
mse_train_act.lkflag.hcp = sum((y.train[abs(y.train)>act]-train_pred_lkflag.hcp[abs(y.train)>act])^2)/sum(abs(y.train)>act)
mse_test_act.lkflag.hcp = sum((y.test[abs(y.test)>act]-test_pred_lkflag.hcp[abs(y.test)>act])^2)/sum(abs(y.test)>act)

res_list[[3*i-2]][2,num_exp] = mse_train.lkflag.hcp
res_list[[3*i-2]][4,num_exp] = mse_train_act.lkflag.hcp
res_list[[3*i-1]][2,num_exp] = mse_test.lkflag.hcp
res_list[[3*i-1]][4,num_exp] = mse_test_act.lkflag.hcp
res_list[[3*i]][2,num_exp] = as.numeric(t2-t1, units="hours")*3600

# report mse by regions

for(j in 1:nregion) {
  code_cur = aal_region$Code[j]
  region.train = (code.train==code_cur)
  if(sum(region.train)>0) {
    rbf_res[[2*i-1]][j,num_exp] = sum((y.train[region.train]-train_pred.hcp[region.train])^2)/sum(region.train)
    lkflag_res[[2*i-1]][j,num_exp] = sum((y.train[region.train]-train_pred_lkflag.hcp[region.train])^2)/sum(region.train)
  }
  region.test = (code.test==code_cur)
  if(sum(region.test)>0) {
    rbf_res[[2*i]][j,num_exp] = sum((y.test[region.test]-test_pred.hcp[region.test])^2)/sum(region.test)
    lkflag_res[[2*i]][j,num_exp] = sum((y.test[region.test]-test_pred_lkflag.hcp[region.test])^2)/sum(region.test)
  }
}

}
}

time_end = Sys.time()
time_diff = time_end - time_start
```

```{r}
print(time_diff)
```

```{r}
y.rbf = c(1:n); y.lkflag = c(1:n)
y.rbf[train.index] = train_pred.hcp; y.rbf[test.index] = test_pred.hcp
y.lkflag[train.index] = train_pred_lkflag.hcp; y.lkflag[test.index] = test_pred_lkflag.hcp
```

```{r}
idx = (X[,1]==X[20000,1])
mydata = X[idx,2:3]
meas = y[idx]
ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=meas)) +
  scale_color_gradientn(colours = rainbow(10)) +
  xlab("Y") + ylab("Z") + labs(colour="Measured value")
```

```{r}
idx = (X[,1]==X[20000,1])
sd(y[idx])^2
sum((y[idx]-y.rbf[idx])^2)/sum(idx)
sum((y[idx]-y.lkflag[idx])^2)/sum(idx)
```

```{r}
ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=y.rbf[idx])) +
  scale_color_gradientn(colours = rainbow(10)) +
  xlab("Y") + ylab("Z") + labs(colour="Estimated value")
ggsave(paste0("plots/hcp/rbf_slice_1.pdf"))
```

```{r}
ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=y.lkflag[idx])) +
  scale_color_gradientn(colours = rainbow(10)) +
  xlab("Y") + ylab("Z") + labs(colour="Estimated value")
ggsave(paste0("plots/hcp/lkflag_slice_1.pdf"))
```


## manipulate results
```{r}
cat("The number of total samples is n = ",n,":\n", sep = "")
res_table = as.data.frame(matrix(0,nrow=4,ncol=length(ms)*3))
colnames(res_table) = rep(c("train mse", "test mse", "time"), length(ms))
rownames(res_table) = c("RBF GP", "LKFLGP", "Act RBF", "Act LK")

mydigits = 4

for(i in c(1:length(ms))) {
  # time
  res_table[,(3*i)] = round(rowMeans(res_list[[(3*i)]]), digits = mydigits)
  
  train_mse_mean = round(rowMeans(res_list[[(3*i-2)]]), digits = mydigits)
  train_mse_std = round(apply(res_list[[(3*i-2)]], 1, sd), digits = mydigits)
  
  test_mse_mean = round(rowMeans(res_list[[(3*i-1)]]), digits = mydigits)
  test_mse_std = round(apply(res_list[[(3*i-1)]], 1, sd), digits = mydigits)
  
  for(j in c(1:4)) {
    res_table[j,(3*i-2)] = paste0(train_mse_mean[j],"(",train_mse_std[j],")")
    res_table[j,(3*i-1)] = paste0(test_mse_mean[j],"(",test_mse_std[j],")")
  }
}

print(res_table)

```

```{r}
write.csv(res_table, paste0("tables/hcp/",subject,".csv"))
```

```{r}
train_table = as.data.frame(matrix(0,nrow=2*nregion,ncol=length(ms)))
colnames(train_table) = ms
rowname = c(1:(2*nregion))
for(i in 1:nregion) {
  rowname[2*i-1] = paste0(aal_region$Code[i],"_rbf")
  rowname[2*i] = paste0(aal_region$Code[i],"_lkflag")
}
rownames(train_table) = rowname

mydigits = 4

for(i in c(1:length(ms))) {
  for(j in c(1:nregion)) {
    train_mse_mean_rbf = round(mean(rbf_res[[(2*i-1)]][j,]), digits = mydigits)
    train_mse_std_rbf = round(sd(rbf_res[[(2*i-1)]][j,]), digits = mydigits)
    train_table[(2*j-1),i] = paste0(train_mse_mean_rbf,"(",train_mse_std_rbf,")")
    
    train_mse_mean_lkflag = round(mean(lkflag_res[[(2*i-1)]][j,]), digits = mydigits)
    train_mse_std_lkflag = round(sd(lkflag_res[[(2*i-1)]][j,]), digits = mydigits)
    train_table[(2*j),i] = paste0(train_mse_mean_lkflag,"(",train_mse_std_lkflag,")")
  }
}

print(head(train_table))

```

```{r}
write.csv(train_table, paste0("tables/hcp/",subject,"_train_region.csv"))
```


```{r}
test_table = as.data.frame(matrix(0,nrow=2*nregion,ncol=length(ms)))
colnames(test_table) = ms
rowname = c(1:(2*nregion))
for(i in 1:nregion) {
  rowname[2*i-1] = paste0(aal_region$Code[i],"_rbf")
  rowname[2*i] = paste0(aal_region$Code[i],"_lkflag")
}
rownames(test_table) = rowname

mydigits = 4

for(i in c(1:length(ms))) {
  for(j in c(1:nregion)) {
    test_mse_mean_rbf = round(mean(rbf_res[[(2*i)]][j,]), digits = mydigits)
    test_mse_std_rbf = round(sd(rbf_res[[(2*i)]][j,]), digits = mydigits)
    test_table[(2*j-1),i] = paste0(test_mse_mean_rbf,"(",test_mse_std_rbf,")")
    
    test_mse_mean_lkflag = round(mean(lkflag_res[[(2*i)]][j,]), digits = mydigits)
    test_mse_std_lkflag = round(sd(lkflag_res[[(2*i)]][j,]), digits = mydigits)
    test_table[(2*j),i] = paste0(test_mse_mean_lkflag,"(",test_mse_std_lkflag,")")
  }
}

print(head(test_table))

```

```{r}
write.csv(test_table, paste0("tables/hcp/",subject,"_test_region.csv"))
```

