---
title: "Reconstruction plot on frontal regions"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

+ read data 

```{r}
library(FLGP)
library(kernlab)
library(readxl)
library(ggplot2)
library(ggpubr)
```

```{r}
subject = "100206"
data = read.csv(paste0("G:/Phd/Data/HCPFMRI/2bk-0bk/",subject,"_2bk-0bk.csv"))
X = as.matrix(data[,1:3])
y = data[,4]
code = data[,5]
```

```{r}
aal_region = read_excel("G:/Phd/Data/HCPFMRI/AALregion_full.xls")
```


```{r}
idx.frontal = is.element(code, aal_region$Code[3:16])
X = X[idx.frontal,]
y = y[idx.frontal]
```

```{r}
act = quantile(abs(y),0.95)
```


```{r}
set.seed(1234)
```


## Experiment
```{r}
n = nrow(X)
m = 5000 # number of labeled samples
```

```{r}
# hyper parameters
s = 1000; r = 3; K = 200
models = list(subsample="kmeans", kernel="lae", gl="cluster-normalized", root=TRUE)
```

```{r, include=FALSE}
time_start = Sys.time()

cat("\n\n##########################################################\n")  
cat(paste0("When m = ",m,", n = ",n, " in fMRI reconstruction:\n\n"))
  

train.index = sample.int(n, m)
test.index = c(1:n)[-train.index]
X.train = X[train.index,]; X.test = X[test.index,]
y.train = y[train.index]; y.test = y[test.index]

# radial basis kernel function
t1 = Sys.time()
rbf.hcp = gausspr(x=X.train, y=y.train)
train_pred.hcp = predict(rbf.hcp, X.train)
test_pred.hcp = predict(rbf.hcp, X.test)
t2 = Sys.time()
t2 - t1

mse_train.rbf.hcp = sum((y.train-train_pred.hcp)^2)/m
mse_test.rbf.hcp = sum((y.test-test_pred.hcp)^2)/(n-m)

mse_train_act.rbf.hcp = sum((y.train[abs(y.train)>act]-train_pred.hcp[abs(y.train)>act])^2)/sum(abs(y.train)>act)
mse_test_act.rbf.hcp = sum((y.test[abs(y.test)>act]-test_pred.hcp[abs(y.test)>act])^2)/sum(abs(y.test)>act)


# Nystrom extension
models$subsample = "kmeans"
t1 = Sys.time()
res_nystrom.hcp = fit_nystrom_regression_gp_rcpp(X.train, y.train, X.test, s, K, models = models, noise = "same")
t2 = Sys.time()
y_nystrom.hcp = res_nystrom.hcp$Y_pred
train_pred_nystrom.hcp = y_nystrom.hcp$train
test_pred_nystrom.hcp = y_nystrom.hcp$test

mse_train.nystrom.hcp = sum((y.train-train_pred_nystrom.hcp)^2)/m
mse_test.nystrom.hcp = sum((y.test-test_pred_nystrom.hcp)^2)/(n-m)
mse_train_act.nystrom.hcp = sum((y.train[abs(y.train)>act]-train_pred_nystrom.hcp[abs(y.train)>act])^2)/sum(abs(y.train)>act)
mse_test_act.nystrom.hcp = sum((y.test[abs(y.test)>act]-test_pred_nystrom.hcp[abs(y.test)>act])^2)/sum(abs(y.test)>act)



# LKFLGP
models$subsample = "kmeans"; models$gl = "cluster-normalized"
t1 = Sys.time()
res_lkflag.hcp = fit_lae_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models, noise = "same")
t2 = Sys.time()
t2 - t1

y_lkflag.hcp = res_lkflag.hcp$Y_pred
train_pred_lkflag.hcp = y_lkflag.hcp$train
test_pred_lkflag.hcp = y_lkflag.hcp$test

mse_train.lkflag.hcp = sum((y.train-train_pred_lkflag.hcp)^2)/m
mse_test.lkflag.hcp = sum((y.test-test_pred_lkflag.hcp)^2)/(n-m)
mse_train_act.lkflag.hcp = sum((y.train[abs(y.train)>act]-train_pred_lkflag.hcp[abs(y.train)>act])^2)/sum(abs(y.train)>act)
mse_test_act.lkflag.hcp = sum((y.test[abs(y.test)>act]-test_pred_lkflag.hcp[abs(y.test)>act])^2)/sum(abs(y.test)>act)


time_end = Sys.time()
time_diff = time_end - time_start
```

```{r}
print(time_diff)
```

```{r}
y.rbf = c(1:n); y.nystrom = c(1:n); y.lkflag = c(1:n)
y.rbf[train.index] = train_pred.hcp; y.rbf[test.index] = test_pred.hcp
y.nystrom[train.index] = train_pred_nystrom.hcp; y.nystrom[test.index] = test_pred_nystrom.hcp
y.lkflag[train.index] = train_pred_lkflag.hcp; y.lkflag[test.index] = test_pred_lkflag.hcp
```

+ Prediction

+ Truth
```{r}
idx = (X[,1]==X[5000,1])
mydata = X[idx,2:3]
meas = y[idx]
rng.reg = range(y[idx],y.rbf[idx],y.nystrom[idx],y.lkflag[idx])
p1.reg <- ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=meas),size=0.8) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=rng.reg) +
  xlab("Y") + ylab("Z") + labs(colour="") +
  theme(legend.key.width = unit(1.5, "cm"))
ggsave(paste0("plots/hcp/frontal/truth.pdf"),p1.reg)
```

```{r}
sd(y[idx])^2
sum((y[idx]-y.rbf[idx])^2)/sum(idx)
sum((y[idx]-y.nystrom[idx])^2)/sum(idx)
sum((y[idx]-y.lkflag[idx])^2)/sum(idx)
```

+ RBF
```{r}
p2.reg <- ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=y.rbf[idx]),size=0.8) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=rng.reg) +
  xlab("Y") + ylab("Z") + labs(colour="")
ggsave(paste0("plots/hcp/frontal/rbf.pdf"),p2.reg)
```

+ Nystrom extension
```{r}
p3.reg <- ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=y.nystrom[idx]),size=0.8) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=rng.reg) +
  xlab("Y") + ylab("Z") + labs(colour="")
ggsave(paste0("plots/hcp/frontal/nystrom.pdf"),p3.reg)
```

+ LKFLGP
```{r}
p4.reg <- ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=y.lkflag[idx]),size=0.8) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=rng.reg) +
  xlab("Y") + ylab("Z") + labs(colour="")
ggsave(paste0("plots/hcp/frontal/lkflag.pdf"),p4.reg)
```

+ Arrange on one page
```{r}
plot.reg = ggarrange(p1.reg,p2.reg,p3.reg,p4.reg,
                    ncol=2,nrow=2,
                    common.legend=TRUE)
ggexport(plot.reg, filename = "plots/hcp/frontal/prediction.pdf")
```

+ Difference

+ RBF
```{r}
rng.dif = range(y.rbf[idx]-y[idx],
                y.nystrom[idx]-y[idx],
                y.lkflag[idx]-y[idx])
```

```{r}
p1.dif <- ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=y.rbf[idx]-y[idx]),size=0.8) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=rng.dif) +
  xlab("Y") + ylab("Z") + labs(colour="") + theme(legend.key.width = unit(1.5, "cm")) +
  geom_rect(aes(xmin=0.62,xmax=0.68,ymin=0.51,ymax=0.58),fill="transparent",color="black") +
  geom_text(aes(x=0.65,y=0.49,label="1")) + 
  geom_rect(aes(xmin=0.71,xmax=0.76,ymin=0.44,ymax=0.49),fill="transparent",color="black") +
  geom_text(aes(x=0.70,y=0.465,label="2"))
ggsave(paste0("plots/hcp/frontal/diff_rbf.pdf"),p1.dif)
```

+ Nystrom extension
```{r}
p2.dif <- ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=y.nystrom[idx]-y[idx]),size=0.8) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=rng.dif) +
  xlab("Y") + ylab("Z") + labs(colour="") +
  geom_rect(aes(xmin=0.62,xmax=0.68,ymin=0.51,ymax=0.58),fill="transparent",color="black") +
  geom_text(aes(x=0.65,y=0.49,label="1")) + 
  geom_rect(aes(xmin=0.71,xmax=0.76,ymin=0.44,ymax=0.49),fill="transparent",color="black") +
  geom_text(aes(x=0.70,y=0.465,label="2"))
ggsave(paste0("plots/hcp/frontal/diff_nystrom.pdf"),p2.dif)
```

+ LKFLGP
```{r}
p3.dif <- ggplot() + geom_point(aes(mydata[,1],mydata[,2],color=y.lkflag[idx]-y[idx]),size=0.8) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=rng.dif) +
  xlab("Y") + ylab("Z") + labs("") +
  geom_rect(aes(xmin=0.62,xmax=0.68,ymin=0.51,ymax=0.58),fill="transparent",color="black") +
  geom_text(aes(x=0.65,y=0.49,label="1")) + 
  geom_rect(aes(xmin=0.71,xmax=0.76,ymin=0.44,ymax=0.49),fill="transparent",color="black") +
  geom_text(aes(x=0.70,y=0.465,label="2"))
ggsave(paste0("plots/hcp/frontal/diff_lkflag.pdf"),p3.dif)
```
+ Arrange on one page
```{r}
plot.dif = ggarrange(p1.dif,p2.dif,p3.dif,
                    ncol=2,nrow=2,
                    common.legend=TRUE)
ggexport(plot.dif, filename = "plots/hcp/frontal/difference.pdf")
```
