---
title: "Spiral"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(FLGP)
library(kernlab)
library(ggplot2)
library(ggpubr)
library(latex2exp)
```

+ spiral case

+ Plot the spiral
```{r}
n = 4000
theta = seq(0, 8*pi, length.out=n)
X = cbind((theta+4)^(0.7)*cos(theta), (theta+4)^(0.7)*sin(theta))
```

```{r}
p0 <- ggplot() + geom_path(aes(X[,1],X[,2]), color="gray") +
  xlab("") + ylab("") + ggtitle("")

n_start = 1; n_end = 2000

p0 <- p0 + geom_point(aes(x=X[c(n_start,n_end),1],y=X[c(n_start,n_end),2]))

p0 <- p0 + geom_text(aes(x=X[n_start,1],y=X[n_start,2],label="x"),hjust=2)
p0 <- p0 + geom_text(aes(x=X[n_end,1],y=X[n_end,2],label="x'"),hjust=-1)

p0 <- p0 + geom_path(aes(X[n_start:n_end,1],X[n_start:n_end,2]), color="black", linewidth=1) +
  xlab("") + ylab("") + ggtitle("")

p0 <- p0 + geom_segment(aes(x=X[n_start,1],y=X[n_start,2],xend=X[n_end,1],yend=X[n_end,2]), color="black", linewidth=1, linetype="dotted") +
  xlab("") + ylab("") + ggtitle("")

# ggsave("plots/spiral/manifold.pdf")
```


```{r}
dis = c(0); euc_dis = c(0)
for(i in c(1:(n-1))) {
  dis = c(dis, sqrt(sum((X[i+1,]-X[i,])^2)))
  euc_dis = c(euc_dis, sqrt(sum((X[i+1,]-X[1,])^2)))
}

geo_dis = cumsum(dis)
```

```{r}
hk = exp(-geo_dis^2/2000)
```


```{r}
p1 <- ggplot() + geom_point(aes(X[,1],X[,2],color=hk),size=0.5) +
  scale_color_gradientn(colours = c("blue","green","red")) +
  xlab("") + ylab("") + ggtitle("") + labs(colour="") +
  theme(plot.title = element_text(hjust = 0.5),legend.key.width = unit(1.5, "cm"))

p1 <- p1 + geom_text(aes(x=X[n_start,1],y=X[n_start,2],label="x"),hjust=2)
p1 <- p1 + geom_text(aes(x=X[n_end,1],y=X[n_end,2],label="x'"),hjust=-1)
```

```{r}
sek = exp(-euc_dis^2/60)
```

```{r}
p2 <- ggplot() + geom_point(aes(X[,1],X[,2],color=sek),size=0.5) +
  scale_color_gradientn(colours = c("blue","green","red")) +
  xlab("") + ylab("") + ggtitle("") +
  theme(plot.title = element_text(hjust = 0.5))

p2 <- p2 + geom_text(aes(x=X[n_start,1],y=X[n_start,2],label="x"),hjust=2)
p2 <- p2 + geom_text(aes(x=X[n_end,1],y=X[n_end,2],label="x'"),hjust=-1)
```

```{r}
s = 200; r = 3; K = 100
models = list(subsample = "kmeans", kernel = "lae", gl = "cluster-normalized", root =
    TRUE) 
```

```{r}
flk = heat_kernel_covariance_rcpp(X[1,,drop=FALSE],X[-1,],s,r,5000,K,models = models)
```

```{r}
flk = c(flk)/flk[1]
p3 <- ggplot() + geom_point(aes(X[,1],X[,2],color=flk),size=0.5) +
  scale_color_gradientn(colours = c("blue","green","red")) +
  xlab("") + ylab("") + ggtitle("") +
  theme(plot.title = element_text(hjust = 0.5))

p3 <- p3 + geom_text(aes(x=X[n_start,1],y=X[n_start,2],label="x"),hjust=2)
p3 <- p3 + geom_text(aes(x=X[n_end,1],y=X[n_end,2],label="x'"),hjust=-1)
```

+ Arrange on one page
```{r}
plot.cov = ggarrange(p0,p1,p2,p3,
                    ncol=2,nrow=2,
                    common.legend=TRUE)
ggexport(plot.cov, filename = "plots/spiral/kernel.pdf")
```

+ Simulation
```{r}
set.seed(1234)
```


```{r}
# n = 2000
# theta = runif(n,0,8*pi)
# X = cbind((theta+4)^(0.7)*cos(theta), (theta+4)^(0.7)*sin(theta))
Y = 3*sin(theta/10) + 3*cos(theta/2) + 4*sin(4*theta/5)
```


```{r}
ggplot() + geom_point(aes(X[,1],X[,2]),size=0.5) +
  xlab(TeX("$X_1$")) + ylab(TeX("$X_2$"))
ggsave("plots/spiral/allpoints.pdf")
```

```{r}
s = 200
I = subsample_cpp(X, s)
```

```{r}
ggplot() + geom_point(aes(I[,1],I[,2]),size=0.5) +
  xlab(TeX("$X_1$")) + ylab(TeX("$X_2$"))
ggsave("plots/spiral/subsamplepoints.pdf")
```

```{r}
ggplot() + geom_point(aes(X[,1],X[,2],color=Y)) +
  scale_color_gradientn(colours = rainbow(10))
```


```{r}
m = 200
train.index = sample.int(n,m); test.index = c(1:n)[-train.index]
X.train = X[train.index,]; Y.train = Y[train.index]
X.test = X[test.index,]; Y.test = Y[test.index]
Yobs.train = Y.train + rnorm(m,0,1)
```

```{r}
sqrt(sum((Y.test-mean(Yobs.train))^2)/(n-m))
```


```{r}
s = 200; r = 3; K = 100
```

+ LKFLGP

```{r}
t1 = Sys.time()
res_pred_lkflag = fit_lae_regression_gp_rcpp(X.train,Yobs.train,X.test,s,r,K)
t2 = Sys.time()
t2-t1
```

```{r}
Y_pred_lkflag = res_pred_lkflag$Y_pred
# sqrt(sum((Y.train-Y_pred_lkflag$train)^2)/(n-m))
sqrt(sum((Y.test-Y_pred_lkflag$test)^2)/(n-m))
```

```{r}
ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_lkflag$test)) +
  scale_color_gradientn(colours = rainbow(10)) + 
  geom_point(aes(X.train[,1],X.train[,2]),color="black", size=0.7)
```

+ SKFLGP

```{r}
t1 = Sys.time()
res_pred_skflag = fit_se_regression_gp_rcpp(X.train,Yobs.train,X.test,s,r,K)
t2 = Sys.time()
t2 - t1
```

```{r}
Y_pred_skflag = res_pred_skflag$Y_pred
sqrt(sum((Y.test-Y_pred_skflag$test)^2)/(n-m))
```

```{r}
ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_skflag$test)) +
  scale_color_gradientn(colours = rainbow(10)) +
  geom_point(aes(X.train[,1],X.train[,2]),color="black", size=0.7)
```

+ RBF

```{r}
t1 = Sys.time()
rbf.spiral = gausspr(X.train,Yobs.train)
Y_pred_rbf = predict(rbf.spiral, X.test)
t2 = Sys.time()
t2 - t1
sqrt(sum((Y.test-Y_pred_rbf)^2)/(n-m))
```

```{r}
ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_rbf)) +
  scale_color_gradientn(colours = rainbow(10)) +
  geom_point(aes(X.train[,1],X.train[,2]),color="black", size=0.7)
```

+ Plot in one page

```{r}
range_y = range(Y, Yobs.train, Y_pred_lkflag, Y_pred_rbf)
```

```{r}
# ground truth
p1 <- ggplot() + geom_point(aes(X[,1],X[,2],color=Y),size=0.5) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=range_y) +
  xlab("") + ylab("") + ggtitle("") + labs(colour="") +
  theme(plot.title = element_text(hjust = 0.5),legend.key.width = unit(1.5, "cm"))

# output over training points
p2 <- ggplot() + geom_point(aes(X.train[,1],X.train[,2],color=Yobs.train),size=0.5) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=range_y) +
  xlab("") + ylab("") + ggtitle("") +
  theme(plot.title = element_text(hjust = 0.5))

# prediction by FLGP
p3 <- ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_lkflag$test),size=0.5) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=range_y) +
  xlab("") + ylab("") + ggtitle("") +
  theme(plot.title = element_text(hjust = 0.5))

# prediction by RBF GP
p4 <- ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_rbf),size=0.5) +
  scale_color_gradientn(colours = c("blue","green","red"),limits=range_y) +
  xlab("") + ylab("") + ggtitle("") +
  theme(plot.title = element_text(hjust = 0.5))
```

+ Arrange on one page
```{r}
plot.pred = ggarrange(p1,p2,p3,p4,
                    ncol=2,nrow=2,
                    common.legend=TRUE)
ggexport(plot.pred, filename = "plots/spiral/prediction.pdf")
```

```{r}
plot.spiral = ggarrange(p0,p1,p3,p4,
                    ncol=2,nrow=2,
                    common.legend=TRUE)
ggexport(plot.spiral, filename = "plots/spiral/spiral.pdf")
```



+ GLGP

```{r}
t1 = Sys.time()
Y_pred_gl = fit_gl_regression_gp_rcpp(X.train,Yobs.train,X.test,K,sparse = FALSE)
t2 = Sys.time()
t2 - t1
```

```{r}
sqrt(sum((Y.test-Y_pred_gl$test)^2)/(n-m))
```

```{r}
ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_gl$test)) +
  scale_color_gradientn(colours = rainbow(10)) +
  geom_point(aes(X.train[,1],X.train[,2]),color="black", size=0.7)
```


```{r}
ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_gl$test-Y.test)) +
  scale_color_gradientn(colours = rainbow(10)) +
  geom_point(aes(X.train[,1],X.train[,2]),color="black", size=0.7)
```


```{r}
ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_lkflag$test-Y.test)) +
  scale_color_gradientn(colours = rainbow(10)) +
  geom_point(aes(X.train[,1],X.train[,2]),color="black", size=0.7)
```

```{r}
ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_skflag$test-Y.test)) +
  scale_color_gradientn(colours = rainbow(10)) +
  geom_point(aes(X.train[,1],X.train[,2]),color="black", size=0.7)
```

```{r}
ggplot() + geom_point(aes(X.test[,1],X.test[,2],color=Y_pred_rbf-Y.test)) +
  scale_color_gradientn(colours = rainbow(10)) +
  geom_point(aes(X.train[,1],X.train[,2]),color="black", size=0.7)
```
