---
title: "Brain Summary"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

+ Summary Data
```{r}
# TO DO
pathpre = "path to data file directory"
# pathpre = "G:/Phd/Data/HCPFMRI/WM_contrasts"
```


```{r}
options(scipen=999)
index.subject = read.csv(file.path(pathpre, "index2bk-0bk.csv"))
nsub = dim(index.subject)[1]
# nsub = 5
```

```{r}
msets = array(NA, c(4, 3, nsub))
mses = array(NA, c(4, 3, nsub))
nlls = array(NA, c(4, 3, nsub))
times = array(NA, c(4, 3, nsub))
```

```{r}
for(idx in c(1:nsub)) {
  subject = index.subject$subject[idx]
  load(file = file.path(pathpre, "tables/brain", paste0(subject,".Rdata")))
  for(i in c(1:4)) {
    for(j in c(1:3)) {
      msets[i,j,idx] = mean(mset[i,,j])
      mses[i,j,idx] = mean(mse[i,,j])
      nlls[i,j,idx] = mean(nll[i,,j])
      times[i,j,idx] = mean(time[i,,j])
    }
  }
}
```

```{r}
result.brain = data.frame(array(dim=c(4,12)))
rownames(result.brain) = c("RBF GP", "GLGP*", "SKFLGP", "LKFLGP")
colnames(result.brain) = rep(c("Train MSE", "Test MSE", "NLL", "Time"),times=3)
```

```{r}
digits = 3
for(i in 1:4) {
  for(j in 1:3) {
    result.brain[i,(4*j-3)] = paste0(round(mean(msets[i,j,]),digits),"(",round(sd(msets[i,j,]),digits),")")
    result.brain[i,(4*j-2)] = paste0(round(mean(mses[i,j,]),digits),"(",round(sd(mses[i,j,]),digits),")")
    result.brain[i,(4*j-1)] = paste0(round(mean(nlls[i,j,]),digits),"(",round(sd(nlls[i,j,]),digits),")")
    result.brain[i,(4*j)] = round(mean(times[i,j,]), 1)
  }
}
print(result.brain)
write.csv(result.brain, file.path(pathpre, "tables", "summary_brain.csv"))
```
