---
title: "Frontal Activated Region in Single Subject"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(oro.nifti)
library(neurobase)
library(readxl)
library(FLGP)
library(kernlab)
```

## read data
```{r}
subject = "100307"
data = read.csv(paste0("G:/Phd/Data/HCPFMRI/2bk-0bk/frontal/",subject,"_2bk-0bk_frontal.csv"))
act_count = readnii(paste0("G:/Phd/Data/HCPFMRI/2bk-0bk/activated_90.nii"))
```

```{r}
# Activated Location
I = dim(data)[1]
act_idx = rep(NA,I)
act_idx = sapply(c(1:I), function(i) {
  return(act_count[data[i,1],data[i,2],data[i,3]]>=3)
})
```

```{r}
data_act = data[act_idx,]
X = as.matrix(data_act[,1:3])
X = apply(X,2,function(x) {return((x-min(x))/(max(x)-min(x)))}) # coordinate transform
y = data_act[,4]
```


## Experiment
```{r}
set.seed(1234)
```

```{r}
n = nrow(X)
num_exps = 1 # experiment numbers
ms = c(500,1000,2000,3000) # number of labeled samples
a = 0.01
res_list = lapply(c(1:(length(ms)*3)), function(i) {return(matrix(NA,nrow=3,ncol=num_exps))})
```

```{r}
# hyper parameters
s = 600; r = 3; K = 300
models = list(subsample="kmeans", kernel="lae", gl="cluster-normalized", root=TRUE)
```

```{r, include=FALSE}
time_start = Sys.time()

for(i in c(1:length(ms))) {

for(num_exp in c(1:num_exps)) {
  

cat("\n\n##########################################################\n")  
cat(paste0("When m = ",ms[i],", the ",num_exp, "-th experiment:\n\n"))
  
# regression
m = ms[i]
train.index = sample.int(n, m)
test.index = c(1:n)[-train.index]
X.train = X[train.index,]; X.test = X[test.index,]
y.train = y[train.index]; y.test = y[test.index]

# radial basis kernel function
t1 = Sys.time()
rbf.hcp = gausspr(x=X.train, y=y.train)
train_pred.hcp = predict(rbf.hcp, X.train)
test_pred.hcp = predict(rbf.hcp, X.test)
t2 = Sys.time()
mse_train.rbf.hcp = mean((y.train-train_pred.hcp)^2)
mse_test.rbf.hcp = mean((y.test-test_pred.hcp)^2)
mse_test.rbf.win = mean(sort((y.test-test_pred.hcp)^2)[round((n-m)*a):round((n-m)*(1-a))])

res_list[[3*i-2]][1,num_exp] = mse_train.rbf.hcp
res_list[[3*i-1]][1,num_exp] = mse_test.rbf.win
res_list[[3*i]][1,num_exp] = as.numeric(t2-t1, units="hours")*3600


# GLGP
t1 = Sys.time()
res_glgp.hcp = fit_gl_regression_gp_rcpp(X.train, y.train, X.test, K, models = models, noise = "same", sigma = 1e-2, sparse = FALSE)
t2 = Sys.time()
t2 - t1
y_glgp.hcp = res_glgp.hcp$Y_pred
train_pred_glgp.hcp = y_glgp.hcp$train
test_pred_glgp.hcp = y_glgp.hcp$test

mse_train.glgp.hcp = mean((y.train-train_pred_glgp.hcp)^2)
mse_test.glgp.hcp = mean((y.test-test_pred_glgp.hcp)^2)
mse_test.glgp.win = mean(sort((y.test-test_pred_glgp.hcp)^2)[round((n-m)*a):round((n-m)*(1-a))])

res_list[[3*i-2]][2,num_exp] = mse_train.glgp.hcp
res_list[[3*i-1]][2,num_exp] = mse_test.glgp.win
res_list[[3*i]][2,num_exp] = as.numeric(t2-t1, units="hours")*3600

if(TRUE) {
# Nystrom extension
models$subsample = "kmeans"
t1 = Sys.time()
res_nystrom.hcp = fit_nystrom_regression_gp_rcpp(X.train, y.train, X.test, s, K, models = models, noise = "same", sigma = 1e-2)
t2 = Sys.time()
y_nystrom.hcp = res_nystrom.hcp$Y_pred
train_pred_nystrom.hcp = y_nystrom.hcp$train
test_pred_nystrom.hcp = y_nystrom.hcp$test

mse_train.nystrom.hcp = mean((y.train-train_pred_nystrom.hcp)^2)
mse_test.nystrom.hcp = mean((y.test-test_pred_nystrom.hcp)^2)
mse_test.nystrom.win = mean(sort((y.test-test_pred_nystrom.hcp)^2)[round((n-m)*a):round((n-m)*(1-a))])

res_list[[3*i-2]][3,num_exp] = mse_train.nystrom.hcp
res_list[[3*i-1]][3,num_exp] = mse_test.nystrom.win
res_list[[3*i]][3,num_exp] = as.numeric(t2-t1, units="hours")*3600
}


# LKFLGP
models$subsample = "kmeans"; models$gl = "cluster-normalized"
t1 = Sys.time()
res_lkflag.hcp = fit_lae_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models, noise = "same", sigma = 1e-3)
t2 = Sys.time()
y_lkflag.hcp = res_lkflag.hcp$Y_pred
train_pred_lkflag.hcp = y_lkflag.hcp$train
test_pred_lkflag.hcp = y_lkflag.hcp$test

mse_train.lkflag.hcp = mean((y.train-train_pred_lkflag.hcp)^2)
mse_test.lkflag.hcp = mean((y.test-test_pred_lkflag.hcp)^2)
mse_test.lkflag.win = mean(sort((y.test-test_pred_lkflag.hcp)^2)[round((n-m)*a):round((n-m)*(1-a))])

res_list[[3*i-2]][4,num_exp] = mse_train.lkflag.hcp
res_list[[3*i-1]][4,num_exp] = mse_test.lkflag.win
res_list[[3*i]][4,num_exp] = as.numeric(t2-t1, units="hours")*3600


if(FALSE) {
# SKFLGP
models$subsample = "kmeans"; models$gl = "cluster-normalized"
t1 = Sys.time()
res_skflag.hcp = fit_se_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models, noise = "same", sigma = 1e-3)
t2 = Sys.time()
y_skflag.hcp = res_skflag.hcp$Y_pred
train_pred_skflag.hcp = y_skflag.hcp$train
test_pred_skflag.hcp = y_skflag.hcp$test

mse_train.skflag.hcp = mean((y.train-train_pred_skflag.hcp)^2)
mse_test.skflag.hcp = mean((y.test-test_pred_skflag.hcp)^2)
mse_test.skflag.win = mean(sort((y.test-test_pred_skflag.hcp)^2)[round((n-m)*a):round((n-m)*(1-a))])


res_list[[3*i-2]][4,num_exp] = mse_train.skflag.hcp
# res_list[[3*i-1]][7,num_exp] = mse_test.skflag.hcp
res_list[[3*i-1]][4,num_exp] = mse_test.skflag.win
res_list[[3*i]][4,num_exp] = as.numeric(t2-t1, units="hours")*3600
}

}
}

time_end = Sys.time()
time_diff = time_end - time_start
```

```{r}
print(time_diff)
```


## manipulate results
```{r}
cat("The number of total samples is n = ",n,":\n", sep = "")
res_table = as.data.frame(matrix(0,nrow=4,ncol=length(ms)*3))
colnames(res_table) = rep(c("train mse", "test mse", "time"), length(ms))
rownames(res_table) = c("RBF GP", "GLGP", "Nystrom", "LKFLGP")

mydigits = 3

for(i in c(1:length(ms))) {
  # time
  res_table[,(3*i)] = round(rowMeans(res_list[[(3*i)]]), digits = mydigits)
  
  train_mse_mean = round(rowMeans(res_list[[(3*i-2)]]), digits = mydigits)
  train_mse_std = round(apply(res_list[[(3*i-2)]], 1, sd), digits = mydigits)
  
  test_mse_mean = round(rowMeans(res_list[[(3*i-1)]]), digits = mydigits)
  test_mse_std = round(apply(res_list[[(3*i-1)]], 1, sd), digits = mydigits)
  
  for(j in c(1:4)) {
    res_table[j,(3*i-2)] = paste0(train_mse_mean[j],"(",train_mse_std[j],")")
    res_table[j,(3*i-1)] = paste0(test_mse_mean[j],"(",test_mse_std[j],")")
  }
}

print(res_table)

```
