---
title: "Circle example"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(ggpubr)
library(kernlab)
library(FLGP)
```

```{r}
#######################################################
# The first example
# Torus examples

set.seed(1234)
```

```{r}
# generate samples of torus
n = 9000; n_each = 1500; d = 3
thetas = runif(n, 0, 2*pi)
X = matrix(0, nrow=n, ncol=2); Y = matrix(0, nrow=n, ncol=1)
X[,1] = cos(thetas); X[,2] = sin(thetas)
for(i in 0:5) {
  X[(i*n_each+1):((i+1)*n_each),] = (0.5+0.1*i)*X[(i*n_each+1):((i+1)*n_each),]
  Y[(i*n_each+1):((i+1)*n_each),] = as.numeric((-1)^i>0)
}

Y = as.factor(Y)
torus.df = data.frame(X,Y)
```


```{r}
# classification
m = 50
train.index = sample.int(n, m); test.index = c(1:n)[-train.index]
train.data = torus.df[train.index,]; test.data = torus.df[-train.index,]
colnames(torus.df)[3] = "Class"
```

```{r, fig.width=10, fig.height=10}
ggplot() + geom_point(aes(X1,X2,color=Class), data=torus.df, size=0.6, alpha=0.6) +
  scale_color_manual(values = c("red", "orange")) + 
  theme(legend.position="none", 
        axis.title.x=element_blank(), axis.title.y=element_blank())
```

```{r}
# ggsave("plots/circles/truth.pdf", width = 7, height = 7, units = "in", dpi=300)
```


```{r}
# radial basis kernel function
rbf.torus = gausspr(x=train.data[,1:2], y=train.data[,3], type="classification")
# a = 0.7752254
pred_prob.torus = predict(rbf.torus, test.data[,1:2], type="probabilities")
pred_label.torus = as.factor(apply(pred_prob.torus, 1, function(x) {return(which.max(x)-1)}))
err.rbf.torus = sum((as.double(test.data[,3])!=as.double(pred_label.torus))^2)/(n-m)
err.rbf.torus
```

```{r}
kernel = rbf.torus@kernelf
scale = rbf.torus@scaling$x.scale
train.data.scale = scale(train.data[,1:2], scale$`scaled:center`, scale$`scaled:scale`)
test.data.scale = scale(test.data[,1:2], scale$`scaled:center`, scale$`scaled:scale`)
C11 = kernelMatrix(kernel, train.data.scale)
C21 = kernelMatrix(kernel, test.data.scale, train.data.scale)
C22 = rep(1,n-m)
```

```{r}
post = posterior_distribution_classification(C11,C21,cbind(C22),(as.numeric(train.data[,3])-1))
mean = cbind(post$mean)
cov = cbind(post$cov)
nll_rbf = negative_log_likelihood(mean, cov, (as.numeric(test.data[,3])-1), "binary")
nll_rbf
```


```{r}
# ksvm
ksvm.torus = ksvm(x=as.matrix(train.data[,1:(d-1)]), y=as.factor(train.data[,d]), 
            type="C-svc")
# sigma =  1.11782928223624 
# epsilon = 0.4729141
pred_label.ksvm.torus = predict(ksvm.torus, as.matrix(test.data[,1:(d-1)]))
err.ksvm.torus = sum((test.data[,d]!=pred_label.ksvm.torus)^2)/(n-m)
err.ksvm.torus
```


```{r}
# plot
pksvm = ggplot() + geom_point(aes(test.data[,1],test.data[,2],color=pred_label.ksvm.torus), size=0.6, alpha=0.6) + 
  scale_color_manual(values = c("red", "orange")) + 
  geom_point(aes(train.data[,1],train.data[,2]), color="black") + 
  theme(legend.position="none", 
        axis.title.x=element_blank(), axis.title.y=element_blank()) + 
  ggtitle("")
```

+ process data

```{r}
# FLGP
# process data
torus.order = torus.df[c(train.index, test.index), ]
X.scale.torus = scale(as.matrix(torus.order[ ,1:(d-1)]), center = TRUE, scale = TRUE)
X.scale.torus = X.scale.torus / sqrt(ncol(X.scale.torus))

f.torus = as.numeric(train.data[,d])-1
f_test.torus = as.numeric(test.data[,d])-1
```

```{r}
# hyper parameters
K = 100
```

+ GLGP
```{r}
# GLGP
t1 = Sys.time()
bandwidth_range = exp(seq(log(0.001),log(1),length.out=20))
res_gl.torus = fit_gl_logit_gp_rcpp(X.scale.torus[1:m,], f.torus, X.scale.torus[(m+1):n,], K, a2s = bandwidth_range, sparse = FALSE, output_cov = TRUE)
y_pred_gl.torus = as.factor(res_gl.torus$Y_pred$test)
t2 = Sys.time()
t2 - t1
```

```{r}
err_gl.torus = sum((test.data[,d]!=y_pred_gl.torus)^2)/(n-m)
err_gl.torus
```

```{r}
mean = cbind(res_gl.torus$posterior$mean)
cov = cbind(res_gl.torus$posterior$cov)
nll_gl.torus = negative_log_likelihood(mean, cov, f_test.torus, "binary")
nll_gl.torus
```

+ Nystrom extension
```{r}
# Nystrom extension
s = 600

t1 = Sys.time()
bandwidth_range = exp(seq(log(0.001),log(1),length.out=20))
res_nystrom.torus = fit_nystrom_logit_gp_rcpp(X.scale.torus[1:m,], f.torus, X.scale.torus[(m+1):n,], s, K, a2s = bandwidth_range, output_cov = TRUE)
y_pred_nystrom.torus = as.factor(res_nystrom.torus$Y_pred$test)
t2 = Sys.time()
t2 - t1
```

```{r}
err_nystrom.torus = sum((test.data[,d]!=y_pred_nystrom.torus)^2)/(n-m)
err_nystrom.torus
```

```{r}
mean = cbind(res_nystrom.torus$posterior$mean)
cov = cbind(res_nystrom.torus$posterior$cov)
nll_nystrom.torus = negative_log_likelihood(mean, cov, f_test.torus, "binary")
nll_nystrom.torus
```

-------------------------------------------------
--- FLGP ---
-------------------------------------------------

+ FLGP without subsampling

```{r}
s = n; r = 60
models = list(subsample="random", gl="normalized", root=TRUE)

t1 = Sys.time()
bandwidth_range = exp(seq(log(0.1),log(10),length.out=20))
res_flag.torus = fit_se_logit_gp_rcpp(X.scale.torus[1:m,], f.torus, X.scale.torus[(m+1):n,], s, r, K, models = models, a2s = bandwidth_range, output_cov = TRUE)
y_pred_flag.torus = as.factor(res_flag.torus$Y_pred$test)
t2 = Sys.time()
t2 - t1
```

```{r}
err_flag.torus = sum((test.data[,d]!=y_pred_flag.torus)^2)/(n-m)
err_flag.torus
```

```{r}
mean = cbind(res_flag.torus$posterior$mean)
cov = cbind(res_flag.torus$posterior$cov)
nll_flag.torus = negative_log_likelihood(mean, cov, f_test.torus, "binary")
nll_flag.torus
```


```{r}
# hyper parameters
s = 600; r = 3
models = list(subsample="kmeans", kernel="lae", gl="cluster-normalized", root=TRUE)
```

+ SRFLGP
```{r}
# SRFLGP
models$subsample = "random"; models$gl = "normalized"
```

```{r}
t1 = Sys.time()
bandwidth_range = exp(seq(log(0.1),log(10),length.out=20))
res_srflag.torus = fit_se_logit_gp_rcpp(X.scale.torus[1:m,], f.torus, X.scale.torus[(m+1):n,], s, r, K, models = models, a2s = bandwidth_range, output_cov = TRUE)
y_pred_srflag.torus = as.factor(res_srflag.torus$Y_pred$test)
t2 = Sys.time()
t2 - t1
```

```{r}
err_srflag.torus = sum((test.data[,d]!=y_pred_srflag.torus)^2)/(n-m)
err_srflag.torus
```

```{r}
mean = cbind(res_srflag.torus$posterior$mean)
cov = cbind(res_srflag.torus$posterior$cov)
nll_sr.torus = negative_log_likelihood(mean, cov, f_test.torus, "binary")
nll_sr.torus
```

+ SKFLGP
```{r}
# SKFLGP
models$subsample = "kmeans"; models$gl = "cluster-normalized"
```

```{r}
t1 = Sys.time()
bandwidth_range = exp(seq(log(0.1),log(10),length.out=20))
res_skflag.torus = fit_se_logit_gp_rcpp(X.scale.torus[1:m,], f.torus, X.scale.torus[(m+1):n,], s, r, K, models = models, a2s = bandwidth_range, output_cov = TRUE)
y_pred_skflag.torus = as.factor(res_skflag.torus$Y_pred$test)
t2 = Sys.time()
t2 - t1
```

```{r}
err_skflag.torus = sum((test.data[,d]!=y_pred_skflag.torus)^2)/(n-m)
err_skflag.torus
```

```{r}
mean = cbind(res_skflag.torus$posterior$mean)
cov = cbind(res_skflag.torus$posterior$cov)
nll_sk.torus = negative_log_likelihood(mean, cov, f_test.torus, "binary")
nll_sk.torus
```

+ LRFLGP
```{r}
# LRFLGP
models$subsample = "random"; models$gl = "normalized"
```

```{r}
t1 = Sys.time()
res_lrflag.torus = fit_lae_logit_gp_rcpp(X.scale.torus[1:m,], f.torus, X.scale.torus[(m+1):n,], s, r, K, models = models, output_cov = TRUE)
y_pred_lrflag.torus = as.factor(res_lrflag.torus$Y_pred$test)
t2 = Sys.time()
t2 - t1
```

```{r}
err_lrflag.torus = sum((test.data[,d]!=y_pred_lrflag.torus)^2)/(n-m)
err_lrflag.torus
```

```{r}
mean = cbind(res_lrflag.torus$posterior$mean)
cov = cbind(res_lrflag.torus$posterior$cov)
nll_lr.torus = negative_log_likelihood(mean, cov, f_test.torus, "binary")
nll_lr.torus
```


+ LKFLGP
```{r}
# LKFLGP
models$subsample = "kmeans"; models$gl = "cluster-normalized"
```


```{r}
t1 = Sys.time()
res_lkflag.torus = fit_lae_logit_gp_rcpp(X.scale.torus[1:m,], f.torus, X.scale.torus[(m+1):n,], s, r, K, models = models, output_cov = TRUE)
y_pred_lkflag.torus = as.factor(res_lkflag.torus$Y_pred$test)
t2 = Sys.time()
t2 - t1
```

```{r}
err_lkflag.torus = sum((test.data[,d]!=y_pred_lkflag.torus)^2)/(n-m)
err_lkflag.torus
```


```{r}
mean = cbind(res_lkflag.torus$posterior$mean)
cov = cbind(res_lkflag.torus$posterior$cov)
nll_lk.torus = negative_log_likelihood(mean, cov, f_test.torus, "binary")
nll_lk.torus
```



## Covariance

```{r}
k = 1
idx = sample.int(n,2000)
```


+ RBF
```{r}
H_rbf.torus = rbind(C11,C21)
cov_rbf.torus = H_rbf.torus[idx,k]/H_rbf.torus[k,k]
Covariance = cov_rbf.torus
p2.cov = ggplot() + geom_point(aes(torus.order[idx,1],torus.order[idx,2],color=Covariance),size=0.4) + 
  scale_color_gradientn(colours = c("steelblue","green","red"),label = function(x) sprintf("%.2f", x)) +
  geom_point(aes(train.data[k,1],train.data[k,2]), color="black", size=1.5) + 
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),
        legend.text = element_text(size = 7)) + labs(colour="") +
  theme(axis.text = element_text(size=7),legend.key.width = unit(2, "cm"))
```

+ GLGP
```{r}
H_gl.torus = res_gl.torus$C
cov_gl.torus = H_gl.torus[idx, k]/H_gl.torus[k,k]
p3.cov = ggplot() + geom_point(aes(torus.order[idx,1],torus.order[idx,2],color=cov_gl.torus),size=0.4) + 
  scale_color_gradientn(colours = c("steelblue","green","red"),label = function(x) sprintf("%.2f", x)) +
  geom_point(aes(train.data[k,1],train.data[k,2]), color="black", size=1.5) + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank()) + labs(colour="") +
  theme(axis.text = element_text(size=7))
```

+ Nystrom extension
```{r}
H_nystrom.torus = res_nystrom.torus$C
cov_nystrom.torus = H_nystrom.torus[idx,k]/H_nystrom.torus[k,k]
p4.cov = ggplot() + geom_point(aes(torus.order[idx,1],torus.order[idx,2],color=cov_nystrom.torus),size=0.4) + 
  scale_color_gradientn(colours = c("steelblue","green","red"),label = function(x) sprintf("%.2f", x)) +
  geom_point(aes(train.data[k,1],train.data[k,2]), color="black", size=1.5) + 
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) + labs(colour="") +
  theme(axis.text = element_text(size=7))
```

+ FLGP without subsampling
```{r}
H_flag.torus = res_flag.torus$C
cov_flag.torus = H_flag.torus[idx,k]/H_flag.torus[k,k]
p5.cov = ggplot() + geom_point(aes(torus.order[idx,1],torus.order[idx,2],color=cov_flag.torus),size=0.4) + 
  scale_color_gradientn(colours = c("steelblue","green","red"),label = function(x) sprintf("%.2f", x)) +
  geom_point(aes(train.data[k,1],train.data[k,2]), color="black", size=1.5) + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank()) + labs(colour="") +
  theme(axis.text = element_text(size=7))
```


+ SRFLGP
```{r}
H_srflag.torus = res_srflag.torus$C
cov_srflag.torus = H_srflag.torus[idx,k]/H_srflag.torus[k,k]
p6.cov = ggplot() + geom_point(aes(torus.order[idx,1],torus.order[idx,2],color=cov_srflag.torus),size=0.4) + 
  scale_color_gradientn(colours = c("steelblue","green","red"),label = function(x) sprintf("%.2f", x)) +
  geom_point(aes(train.data[k,1],train.data[k,2]), color="black", size=1.5) + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank()) + labs(colour="") +
  theme(axis.text = element_text(size=7))
```

+ SKFLGP
```{r}
H_skflag.torus = res_skflag.torus$C
cov_skflag.torus = H_skflag.torus[idx,k]/H_skflag.torus[k,k]
p7.cov = ggplot() + geom_point(aes(torus.order[idx,1],torus.order[idx,2],color=cov_skflag.torus),size=0.4) + 
  scale_color_gradientn(colours = c("steelblue","green","red"),label = function(x) sprintf("%.2f", x)) +
  geom_point(aes(train.data[k,1],train.data[k,2]), color="black", size=1.5) + 
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) + labs(colour="") +
  theme(axis.text = element_text(size=7))
```

+ LRFLGP
```{r}
H_lrflag.torus = res_lrflag.torus$C
cov_lrflag.torus = H_lrflag.torus[idx,k]/H_lrflag.torus[k,k]
p8.cov = ggplot() + geom_point(aes(torus.order[idx,1],torus.order[idx,2],color=cov_lrflag.torus),size=0.4) + 
  scale_color_gradientn(colours = c("steelblue","green","red"),label = function(x) sprintf("%.2f", x)) +
  geom_point(aes(train.data[k,1],train.data[k,2]), color="black", size=1.5) + 
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) + labs(colour="") +
  theme(axis.text = element_text(size=7))
```

+ LKFLGP
```{r}
H_lkflag.torus = res_lkflag.torus$C
cov_lkflag.torus = H_lkflag.torus[idx,k]/H_lkflag.torus[k,k]
p9.cov = ggplot() + geom_point(aes(torus.order[idx,1],torus.order[idx,2],color=cov_lkflag.torus),size=0.4) + 
  scale_color_gradientn(colours = c("steelblue","green","red"),label = function(x) sprintf("%.2f", x)) +
  geom_point(aes(train.data[k,1],train.data[k,2]), color="black", size=1.5) + 
  theme(axis.title.x=element_blank(),axis.title.y=element_blank()) + labs(colour="") +
  theme(axis.text = element_text(size=7))
```

```{r}
p_empty = ggplot() + theme_void()
```


+ Arrange on one page
```{r}
plot.cov = ggarrange(p2.cov,p3.cov,p4.cov,p5.cov,p6.cov,p7.cov,p8.cov,p9.cov,
          ncol=4,nrow=2,
          common.legend = TRUE)
plot.cov
```

```{r}
ggexport(plot.cov, filename = "plots/circles_revision/covariance.pdf")
```




