---
title: "Kernel density plot"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(FLGP)
library(kernlab)
library(ggplot2)
library(ggpubr)
library(latex2exp)
library(Matrix)
library(RSpectra)
```

```{r}
mypath = "G:/Rtext/Rstudio/exampleFLGP/inst/plots/kernel density"
```


+ circle case

```{r}
# generate data
set.seed(1234)
n = 1000
l = floor(n/2) + 1
theta = seq(0, 2*pi, length.out=n)
theta_ref = theta[l]
x = cbind(cos(theta), sin(theta))
```

```{r}
ggplot() + geom_path(aes(x[,1],x[,2]), color="gray") +
  xlab("") + ylab("") + ggtitle("")
```

+ heat kernel

```{r}
compute_heat_kernel <- function(theta, t, trunc=100) {
  value = rep(0, length(theta))
  for(k in -trunc:trunc) {
    value = value + 1/sqrt(4*pi*t) * exp(-(theta-2*pi*k)^2/(4*t))
  }
  return(value)
}

t = 0.01
y_hk = compute_heat_kernel(theta-theta_ref, t)
```

```{r}
p = ggplot() + geom_path(aes(theta,y_hk), color="red", lwd=1) +
  xlab(TeX("$0\\leq \\theta \\leq 2\\pi$")) + ylab("Kernel Density") + ggtitle("")
p
```


+ squared exponential kernel

```{r}
euclidean_dist = c()
for(i in 1:n) {
  euclidean_dist = c(euclidean_dist, sqrt(sum((x[i,]-x[l,])^2)))
  # euclidean_dist = c(euclidean_dist, sqrt(sum((theta[i]-theta[l])^2)))
}
y_se = 1/sqrt(4*pi*t) * exp(-euclidean_dist^2/(4*t))
```


```{r}
p + geom_path(aes(theta,y_se), color="yellow")
```

+ Fast graph Laplacian estimation

```{r}
s = 200; r = 10; K = 40
bw = 0.05
models = list(subsample = "kmeans", kernel = "se", gl = "cluster-normalized", root =
    TRUE)
cov_fgl = heat_kernel_covariance_rcpp(x[l,,drop=FALSE], x[-l,], s, r, t/bw^2, K, models, bw, nstart = 5)
y_fgl = rep(NA, n)
y_fgl[l] = cov_fgl[1]
y_fgl[-l] = cov_fgl[-1]
```

```{r}
max(y_fgl)
# scale the kernel estimation
y_fgl = y_fgl/y_fgl[l]/sqrt(4*pi*t)
# y_fgl = y_fgl/ max(y_fgl) * 6
```

```{r}
p + geom_path(aes(theta,y_fgl), color="steelblue", lwd=1)
# ggsave(filename=file.path(mypath, paste0("K=",K,"_r=",r,"_hk.pdf")), p, width=5, height=5)
```

+ Graph Laplacian 

```{r}
GL <- function(x, t, K, bandwidth, l) {
  Z = exp(-as.matrix(dist(x))^2/(4*bandwidth^2))
  Q = rowSums(Z)
  W = dimScale(Z, d1 = (1/Q))
  D = rowSums(W)
  A = dimScale(W, d1 = sqrt(1/D))
  eigenpairs = eigs_sym(A, K)
  values = 1 - eigenpairs$values
  vectors = rowScale(eigenpairs$vectors, sqrt(1/D))
  vectors = colScale(vectors, sqrt(1/colSums(vectors^2)))
  
  n = nrow(x)
  y = n*vectors%*%cbind(exp(-values*t/bandwidth^2)*vectors[l,])
  return(y[,1])
}
```

```{r}
K = 40
bw = 0.05
y_gl = GL(x, t, K, bw, l)
```

```{r}
max(y_gl)
# scale the kernel estimation
y_gl = y_gl/y_gl[l]/sqrt(4*pi*t)
# y_gl = y_gl / max(y_gl) * 6
```

```{r}
p + geom_path(aes(theta,y_gl), color="orange", lwd=1) + 
  xlab(TeX("$0\\leq \\theta \\leq 2\\pi$")) + ylab("Kernel Density") + ggtitle("")
```

+ Fast graph Laplacian estimation

```{r}
s = 200; r = 10
models = list(subsample = "kmeans", kernel = "se", gl = "cluster-normalized", root =
    TRUE)
cov_fgl = heat_kernel_covariance_rcpp(x[l,,drop=FALSE], x[-l,], s, r, t/bw^2, K, models, bw)
y_fgl = rep(NA, n)
y_fgl[l] = cov_fgl[1]
y_fgl[-l] = cov_fgl[-1]
```

```{r}
p = p + geom_path(aes(theta,y_fgl), color="steelblue", lwd=1.5, linetype="dashed")
ggsave(filename=file.path(mypath, paste0("K=",K,"_r=",r,"_gl.pdf")), p, width=5, height=5)
p
```

