---
title: "FMRI Reconstruct"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(FLAG)
library(kernlab)
```

```{r}
data_100206 = read.csv("G:/Phd/Data/HCPFMRI/1002062bk-0bk.csv")
```

```{r}
X = as.matrix(data_100206[,-4])
y = data_100206[,4]
```

```{r}
set.seed(1234)
```

```{r}
l = 100000
idx = sample.int(nrow(X),l)
X_used = X[idx,]
y_used = y[idx]
```

```{r}
n = nrow(X_used)
m = 1000
index.train = sample.int(n,m); index.test = c(1:n)[-index.train]
X.train = X_used[index.train,]; X.test = X_used[index.test,]
y.train = y_used[index.train]; y.test = y_used[index.test]
```

```{r}
sum((y.train-mean(y.train))^2)/m
```

```{r}
sum((y.test-mean(y.train))^2)/(n-m)
```


```{r}
# hyper parameters in FLAG
s = 5000; r = 3; K = 100
models = list(subsample="kmeans", kernel="lae", gl="cluster-normalized", root=TRUE)
```


+ LKFLAG

```{r}
t1 = Sys.time()
y_lkflag.rec = fit_lae_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models)
t2 = Sys.time()
print(t2 - t1)
# Time difference of 21.04728 secs
```

```{r}
mse_lkflag.train = sum((y.train-y_lkflag.rec$train)^2)/m
mse_lkflag.train
```


```{r}
mse_lkflag.test = sum((y.test-y_lkflag.rec$test)^2)/(n-m)
mse_lkflag.test
# 0.0009314948
```

+ SKFLAG

```{r}
t1 = Sys.time()
y_skflag.rec = fit_se_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models)
t2 = Sys.time()
print(t2 - t1)
# Time difference of 22.33434 secs
```

```{r}
mse_skflag.train = sum((y.train-y_skflag.rec$train)^2)/m
mse_skflag.train
```


```{r}
mse_skflag.test = sum((y.test-y_skflag.rec$test)^2)/(n-m)
mse_skflag.test
# 0.0009314948
```

+ RBF

```{r}
# radial basis kernel function
t1 = Sys.time()
rbf.rec = gausspr(x=X.train, y=y.train)
y_rbf.rec = predict(rbf.rec, X.test)
t2 = Sys.time()
t2 - t1
# Time difference of 5.588134 secs
# RMSE of the training error
mse_rbf.train = sum((y.train-predict(rbf.rec, X.train))^2)/m
mse_rbf.train
mse_rbf.test = sum((y.test-y_rbf.rec)^2)/(n-m)
mse_rbf.test
# 0.009147905
```
