---
title: "HCP example"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(FLAG)
library(kernlab)
library(bigmemory)
```

+ read data

```{r}
inputpath = "G:/Phd/Data/HCPFMRI/"
phenotypics = read.csv(paste0(inputpath, "HCP_phenotypics_u.csv"))
subject = read.csv(paste0(inputpath, "index2bk-0bk.csv"))
wmpca = read.csv(paste0(inputpath, "WM_matrix/pca2bk-0bk.csv"))
```

```{r}
wmfrontal = read.big.matrix(paste0(inputpath, "WM_matrix/frontal.csv"), type = "double")
dim(wmfrontal)
```


```{r}
X = as.matrix(wmfrontal[,])
g_factor = phenotypics$g[subject$index]
```


```{r}
p = ncol(X); n = nrow(X)
for(i in c(1:p)) {
  meancol = mean(X[,i])
  if(sum(X[,i]!=meancol)>0) {
    X[,i] = scale(X[,i])
  }
}
```


+ Regression

```{r}
set.seed(1234)
```


```{r}
n = length(g_factor)
m = 500
index.train = sample.int(n,m); index.test = c(1:n)[-index.train]
X.train = X[index.train,]; X.test = X[index.test,]
y.train = g_factor[index.train]; y.test = g_factor[index.test]
```

```{r}
sum((y.train-mean(y.train))^2)/m
```


```{r}
# hyper parameters in FLAG
s = 100; r = 100; K = 50
models = list(subsample="random", kernel="lae", gl="normalized", root=TRUE)
```

+ LKFLAG

```{r}
t1 = Sys.time()
y_lkflag.gca = fit_lae_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models)
t2 = Sys.time()
print(t2 - t1)
# Time difference of 22.33434 secs
```

```{r}
mse_lkflag.gca = sum((y.test-y_lkflag.gca)^2)/(n-m)
mse_lkflag.gca
# 0.09683834
```

+ SKFLAG

```{r}
t1 = Sys.time()
y_skflag.gca = fit_se_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models)
t2 = Sys.time()
print(t2 - t1)
# Time difference of 22.33434 secs
```

```{r}
mse_skflag.gca = sum((y.test-y_skflag.gca)^2)/(n-m)
mse_skflag.gca
# 0.09683834
```

+ GLGP

```{r}
# GLGP
t1 = Sys.time()
y_gl.gca = fit_gl_regression_gp_rcpp(X.train, y.train, X.test, K, threshold = 1, sparse = FALSE, models = models)
t2 = Sys.time()
t2 - t1
# Time difference of 7.454023 mins
```

```{r}
mse_gl.gca = sum((y.test-y_gl.gca)^2)/(n-m)
mse_gl.gca
# 0.1605866
```


+ RBF

```{r}
# radial basis kernel function
rbf.gca = gausspr(x=X.train, y=y.train, scaled=FALSE)
y_rbf.gca = predict(rbf.gca, X.test)
mse_rbf.gca = sum((y.test-y_rbf.gca)^2)/(n-m)
mse_rbf.gca
# 0.6146482
```

