---
title: "Reconstruct example"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

+ read data 

```{r}
library(FLGP)
library(kernlab)
library(bigmemory)
library(oro.nifti)
library(neurobase)
```

```{r}
data_100206 = read.csv("G:/Phd/Data/HCPFMRI/1002062bk-0bk.csv")
X = as.matrix(data_100206[,-4])
y = data_100206[,4]
```

```{r}
pathpre = "G:/Phd/Data/HCPFMRI/WM_contrasts/Contrasts/"
pathsuf = "_2bk-0bk.nii"
nii_100206 = readnii(paste0(pathpre, 100206, pathsuf))
```

```{r}
set.seed(1234)
```

## Experiment
```{r}
n = nrow(X)
n_used = n
m = 10000
```

```{r}
# hyper parameters
s = 1000; r = 3; K = 200
models = list(subsample="kmeans", kernel="lae", gl="cluster-normalized", root=TRUE)
```

```{r}
train.index = sample.int(n, m)
test.index = sample(c(1:n)[-train.index],n_used-m)
X.train = X[train.index,]; X.test = X[test.index,]
y.train = y[train.index]; y.test = y[test.index]
```

```{r}
t1 = Sys.time()
y_lkflag.hcp = fit_lae_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models)
t2 = Sys.time()
train_pred_lkflag.hcp = y_lkflag.hcp$train
test_pred_lkflag.hcp = y_lkflag.hcp$test

mse_train.lkflag.hcp = sum((y.train-train_pred_lkflag.hcp)^2)/m
mse_test.lkflag.hcp = sum((y.test-test_pred_lkflag.hcp)^2)/(n_used-m)

t2-t1
```

```{r}
y_pred.hcp = rep(NA, n)
y_pred.hcp[train.index] = y_lkflag.hcp$train
y_pred.hcp[test.index] = y_lkflag.hcp$test
```

+ write nii files

```{r}
nii_copy = nii_100206
dims = dim(nii_100206)
domains = !is.na(nii_100206)
```

```{r}
idx = 1
for(i in 1:dims[1]) {
  for(j in 1:dims[2]) {
    for(k in 1:dims[3]) {
      if(domains[i,j,k]) {
        nii_copy[i,j,k] = y_pred.hcp[idx]
        idx = idx + 1
      }
    }
  }
}
```


```{r}
writenii(nii_copy,"niis/flag1002062bk-0bk.nii")
```

