---
title: "Reconstruction plot"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

+ read data 

```{r}
library(FLGP)
library(kernlab)
library(ggplot2)
library(bigmemory)
```

```{r}
# data_100206 = read.csv("G:/Phd/Data/HCPFMRI/1002062bk-0bk.csv")
# X = as.matrix(data_100206[,-4])
# y = data_100206[,4]
```

```{r}
filepath = "G:/Phd/Data/HCPFMRI/2bk-0bk/"
input = read.csv(paste0(filepath, "input.csv"))
X = as.matrix(input)
y = read.big.matrix(paste0(filepath, "output.csv"), type="double")
```

```{r}
set.seed(1234)
```


## Experiment
```{r}
n = nrow(input); q = ncol(y)
n_used = n; q_used = q
num_exps = 10 # experiment numbers
ms = round(exp(seq(log(500),log(100000),length.out=20))) # number of labeled samples
res_list = lapply(c(1:(length(ms)*3)), function(i) {return(rep(0,num_exps))})
```

```{r}
# hyper parameters
s = 1000; r = 3; K = 200
models = list(subsample="kmeans", kernel="lae", gl="cluster-normalized", root=TRUE)
```

```{r, include=FALSE}
time_start = Sys.time()

for(i in c(1:length(ms))) {

for(num_exp in c(1:num_exps)) {
  

cat("\n\n##########################################################\n")  
cat(paste0("When m = ",ms[i],", the ",num_exp, "-th experiment:\n\n"))
  
# regression
m = ms[i]
train.index = sample.int(n, m)
test.index = sample(c(1:n)[-train.index],n_used-m)
X.train = X[train.index,]; X.test = X[test.index,]
y.train = y[train.index,1:q_used]; y.test = y[test.index,1:q_used]
y.train[is.na(y.train)] = 0
test.hcp = !is.na(y.test)


# LKFLGP
models$subsample = "kmeans"; models$gl = "cluster-normalized"
t1 = Sys.time()
y_lkflag.hcp = fit_lae_regression_gp_rcpp(X.train, y.train, X.test, s, r, K, models = models)
t2 = Sys.time()
train_pred_lkflag.hcp = y_lkflag.hcp$train
test_pred_lkflag.hcp = y_lkflag.hcp$test

mse_train.lkflag.hcp = sum((y.train-train_pred_lkflag.hcp)^2)/m/q_used
mse_test.lkflag.hcp = sum((y.test[test.hcp]-test_pred_lkflag.hcp[test.hcp])^2)/sum(test.hcp)

res_list[[3*i-2]][num_exp] = mse_train.lkflag.hcp
res_list[[3*i-1]][num_exp] = mse_test.lkflag.hcp
res_list[[3*i]][num_exp] = as.numeric(t2-t1, units="hours")*3600

}
  
}

time_end = Sys.time()
time_diff = time_end - time_start
```

```{r}
print(time_diff)
```

## manipulate results
```{r}
cat("The number of total samples is n_used = ",n_used,":\n", sep = "")
res_table = as.data.frame(matrix(0,nrow=length(ms),ncol=6))
colnames(res_table) = c("m", "train mse", "train sd", "test mse", "test sd", "time")

mydigits = 4

res_table[,1] = ms

for(i in c(1:length(ms))) {
  # time
  res_table[i,6] = round(mean(res_list[[(3*i)]]), digits = mydigits)
  
  res_table[i,2] = round(mean(res_list[[(3*i-2)]]), digits = mydigits)
  res_table[i,3] = round(sd(res_list[[(3*i-2)]]), digits = mydigits)
  
  res_table[i,4] = round(mean(res_list[[(3*i-1)]]), digits = mydigits)
  res_table[i,5] = round(sd(res_list[[(3*i-1)]]), digits = mydigits)
  
}

print(res_table)
```

```{r}
write.csv(res_table, paste0("tables/hcp_plots","n",n_used,"s",s,"multi.csv"))
```

```{r}
ggplot(data=res_table) + geom_smooth(aes(x=log(m),y=`train mse`),se=FALSE,color="green") +
  geom_smooth(aes(x=log(m),y=`test mse`),se=FALSE,color="red") + 
  geom_hline(yintercept = min(res_table$`test mse`), show.legend = TRUE)
```

```{r}
plot.df = as.data.frame(matrix(0,2*length(ms),4))
colnames(plot.df) = c("m","mse","sd","dataset")
plot.df$m = c(res_table[,1],res_table[,1])
plot.df$mse = c(res_table[,2],res_table[,4])
plot.df$sd = c(res_table[,3],res_table[,5])
plot.df$dataset = as.factor(c(rep("train",length(ms)), rep("test",length(ms))))
```

```{r}
ggplot(data=plot.df,aes(x=log(m),y=mse,color=dataset)) + geom_smooth(se=FALSE) +
  geom_hline(yintercept = min(res_table$`test mse`)) +
  scale_y_continuous(breaks = c(0.03, 0.04, min(res_table$`test mse`), 0.05, 0.06, 0.07, 0.08), 
                     labels = c(0.03, 0.04, round(min(res_table$`test mse`),4), 0.05, 0.06, 0.07, 0.08)) + labs(title = "MSE of LKFLGP in the neuroimaging reconstruction with 917 subjects", y = "MSE", x = "The logarithm of the number of training samples")
ggsave(paste0("plots/mul_rec_mse.pdf"))
```

