---
title: "Reconstruction by regions with multi-subjects"
author: "He Junhui"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


+ read data 

```{r}
library(FLAG)
library(kernlab)
library(readxl)
library(ggplot2)
```

```{r}
## Experiment
num_exps = 10 # experiment numbers
ms = c(5000,10000,15000,20000,25000,30000) # number of labeled samples
res_list = lapply(c(1:(length(ms)*3)), function(i) {return(matrix(0,nrow=4,ncol=num_exps))})
```

```{r}
# hyper parameters
s_ratio = 10; r = 3; K_ratio = 5
models = list(subsample="kmeans", kernel="lae", gl="cluster-normalized", root=TRUE)
```

```{r}
aal_region = read_excel("G:/Phd/Data/HCPFMRI/AALregion_full.xls")
index.subject = read.csv("G:/Phd/Data/HCPFMRI/index2bk-0bk.csv")
nsub = 10; nregion = nrow(aal_region)
```

```{r}
rbf_res = lapply(c(1:(length(ms)*2)), function(i) {return(matrix(0,nrow=nregion,ncol=num_exps))})
lkflag_res = lapply(c(1:(length(ms)*2)), function(i) {return(matrix(0,nrow=nregion,ncol=num_exps))})
```


```{r, include=FALSE}
time_start = Sys.time()

for(idx in c(1:nsub)) {
subject = index.subject$subject[idx]
  
cat("\n\n##########################################################\n")  
cat("The subject",subject,"\n")

data = read.csv(paste0("G:/Phd/Data/HCPFMRI/2bk-0bk/",subject,"_2bk-0bk.csv"))
X = as.matrix(data[,1:3])
y = data[,4]
code = data[,5]

# read data in aal regions
is.allregion = is.element(code, aal_region$Code)
X = X[is.allregion,]; y = y[is.allregion]; code = code[is.allregion]

# activation threshold
act = quantile(abs(y),probs = 0.95)

set.seed(1234)

n = nrow(X)


for(i in c(1:length(ms))) {

for(num_exp in c(1:num_exps)) {
  

cat("\n\n##########################################################\n")  
cat(paste0("When m = ",ms[i],", the ",num_exp, "-th experiment:\n\n"))
  
is.train = rep(FALSE,n)
y_rbf = rep(NA,n); y_lkflag = rep(NA,n)
t_rbf = 0; t_lkflag = 0

for(j in c(1:nregion)) {
  
is.region = is.element(code, aal_region$Code[j])
X.region = X[is.region,]; y.region = y[is.region]
n.region = sum(is.region)

# regression
m.region = round(ms[i]/n*n.region)
train.index = sample.int(n.region, m.region)
test.index = c(1:n.region)[-train.index]
X.train = X.region[train.index,]; X.test = X.region[test.index,]
y.train = y.region[train.index]; y.test = y.region[test.index]

is.train[is.region][train.index] = TRUE; is.train[is.region][test.index] = FALSE

# radial basis kernel function
cat("RBF GP ...\n")
t1 = Sys.time()
rbf.hcp = gausspr(x=X.train, y=y.train)
train_pred.region = predict(rbf.hcp, X.train)
test_pred.region = predict(rbf.hcp, X.test)
t2 = Sys.time()
t_rbf = t_rbf + t2 - t1
y_rbf[is.region][train.index] = train_pred.region
y_rbf[is.region][test.index] = test_pred.region


# LKFLAG
cat("LKFLAG ...\n")
models$subsample = "kmeans"; models$gl = "cluster-normalized"
s.region = round(n.region/s_ratio); K.region = round(s.region/K_ratio)
t1 = Sys.time()
res_lkflag.hcp = fit_lae_regression_gp_rcpp(X.train, y.train, X.test, s.region, r, K.region, models = models)
t2 = Sys.time()
t_lkflag = t_lkflag + t2 - t1
y_lkflag.hcp = res_lkflag.hcp$Y_pred
train_pred_lkflag.region = y_lkflag.hcp$train
test_pred_lkflag.region = y_lkflag.hcp$test

y_lkflag[is.region][train.index] = train_pred_lkflag.region
y_lkflag[is.region][test.index] = test_pred_lkflag.region

}

m = sum(is.train)
y.train = y[is.train]; y.test = y[!is.train]

# calculate mse of RBF
train_pred.hcp = y_rbf[is.train]
test_pred.hcp = y_rbf[!is.train]

mse_train.rbf.hcp = sum((y.train-train_pred.hcp)^2)/m
mse_test.rbf.hcp = sum((y.test-test_pred.hcp)^2)/(n-m)

mse_train_act.rbf.hcp = sum((y.train[abs(y.train)>act]-train_pred.hcp[abs(y.train)>act])^2)/sum(abs(y.train)>act)
mse_test_act.rbf.hcp = sum((y.test[abs(y.test)>act]-test_pred.hcp[abs(y.test)>act])^2)/sum(abs(y.test)>act)

res_list[[3*i-2]][1,num_exp] = mse_train.rbf.hcp
res_list[[3*i-2]][3,num_exp] = mse_train_act.rbf.hcp
res_list[[3*i-1]][1,num_exp] = mse_test.rbf.hcp
res_list[[3*i-1]][3,num_exp] = mse_test_act.rbf.hcp
res_list[[3*i]][1,num_exp] = as.numeric(t_rbf, units="hours")*3600

# calculate mse of LKFLAG
train_pred_lkflag.hcp = y_lkflag[is.train]
test_pred_lkflag.hcp = y_lkflag[!is.train]

mse_train.lkflag.hcp = sum((y.train-train_pred_lkflag.hcp)^2)/m
mse_test.lkflag.hcp = sum((y.test-test_pred_lkflag.hcp)^2)/(n-m)
mse_train_act.lkflag.hcp = sum((y.train[abs(y.train)>act]-train_pred_lkflag.hcp[abs(y.train)>act])^2)/sum(abs(y.train)>act)
mse_test_act.lkflag.hcp = sum((y.test[abs(y.test)>act]-test_pred_lkflag.hcp[abs(y.test)>act])^2)/sum(abs(y.test)>act)

res_list[[3*i-2]][2,num_exp] = mse_train.lkflag.hcp
res_list[[3*i-2]][4,num_exp] = mse_train_act.lkflag.hcp
res_list[[3*i-1]][2,num_exp] = mse_test.lkflag.hcp
res_list[[3*i-1]][4,num_exp] = mse_test_act.lkflag.hcp
res_list[[3*i]][2,num_exp] = as.numeric(t2-t1, units="hours")*3600

# report mse by regions
code.train = code[is.train]; code.test = code[!is.train]

for(j in 1:nregion) {
  code_cur = aal_region$Code[j]
  region.train = (code.train==code_cur)
  if(sum(region.train)>0) {
    rbf_res[[2*i-1]][j,num_exp] = sum((y.train[region.train]-train_pred.hcp[region.train])^2)/sum(region.train)
    lkflag_res[[2*i-1]][j,num_exp] = sum((y.train[region.train]-train_pred_lkflag.hcp[region.train])^2)/sum(region.train)
  }
  region.test = (code.test==code_cur)
  if(sum(region.test)>0) {
    rbf_res[[2*i]][j,num_exp] = sum((y.test[region.test]-test_pred.hcp[region.test])^2)/sum(region.test)
    lkflag_res[[2*i]][j,num_exp] = sum((y.test[region.test]-test_pred_lkflag.hcp[region.test])^2)/sum(region.test)
  }
}

}
}

## manipulate results
cat("The number of total samples is n = ",n,":\n", sep = "")
res_table = as.data.frame(matrix(0,nrow=4,ncol=length(ms)*3))
colnames(res_table) = rep(c("train mse", "test mse", "time"), length(ms))
rownames(res_table) = c("RBF GP", "LKFLAG", "Act RBF", "Act LK")

mydigits = 4

for(i in c(1:length(ms))) {
  # time
  res_table[,(3*i)] = round(rowMeans(res_list[[(3*i)]]), digits = mydigits)
  
  train_mse_mean = round(rowMeans(res_list[[(3*i-2)]]), digits = mydigits)
  train_mse_std = round(apply(res_list[[(3*i-2)]], 1, sd), digits = mydigits)
  
  test_mse_mean = round(rowMeans(res_list[[(3*i-1)]]), digits = mydigits)
  test_mse_std = round(apply(res_list[[(3*i-1)]], 1, sd), digits = mydigits)
  
  for(j in c(1:4)) {
    res_table[j,(3*i-2)] = paste0(train_mse_mean[j],"(",train_mse_std[j],")")
    res_table[j,(3*i-1)] = paste0(test_mse_mean[j],"(",test_mse_std[j],")")
  }
}

print(res_table)

write.csv(res_table, paste0("tables/hcp/regions/",subject,".csv"))

# train mse on all regions
train_table = as.data.frame(matrix(0,nrow=2*nregion,ncol=length(ms)))
colnames(train_table) = ms
rowname = c(1:(2*nregion))
for(i in 1:nregion) {
  rowname[2*i-1] = paste0(aal_region$Code[i],"_rbf")
  rowname[2*i] = paste0(aal_region$Code[i],"_lkflag")
}
rownames(train_table) = rowname

mydigits = 4

for(i in c(1:length(ms))) {
  for(j in c(1:nregion)) {
    train_mse_mean_rbf = round(mean(rbf_res[[(2*i-1)]][j,]), digits = mydigits)
    train_mse_std_rbf = round(sd(rbf_res[[(2*i-1)]][j,]), digits = mydigits)
    train_table[(2*j-1),i] = paste0(train_mse_mean_rbf,"(",train_mse_std_rbf,")")
    
    train_mse_mean_lkflag = round(mean(lkflag_res[[(2*i-1)]][j,]), digits = mydigits)
    train_mse_std_lkflag = round(sd(lkflag_res[[(2*i-1)]][j,]), digits = mydigits)
    train_table[(2*j),i] = paste0(train_mse_mean_lkflag,"(",train_mse_std_lkflag,")")
  }
}

write.csv(train_table, paste0("tables/hcp/regions/",subject,"_train_region.csv"))

# test mse on all regions
test_table = as.data.frame(matrix(0,nrow=2*nregion,ncol=length(ms)))
colnames(test_table) = ms
rowname = c(1:(2*nregion))
for(i in 1:nregion) {
  rowname[2*i-1] = paste0(aal_region$Code[i],"_rbf")
  rowname[2*i] = paste0(aal_region$Code[i],"_lkflag")
}
rownames(test_table) = rowname

mydigits = 4

for(i in c(1:length(ms))) {
  for(j in c(1:nregion)) {
    test_mse_mean_rbf = round(mean(rbf_res[[(2*i)]][j,]), digits = mydigits)
    test_mse_std_rbf = round(sd(rbf_res[[(2*i)]][j,]), digits = mydigits)
    test_table[(2*j-1),i] = paste0(test_mse_mean_rbf,"(",test_mse_std_rbf,")")
    
    test_mse_mean_lkflag = round(mean(lkflag_res[[(2*i)]][j,]), digits = mydigits)
    test_mse_std_lkflag = round(sd(lkflag_res[[(2*i)]][j,]), digits = mydigits)
    test_table[(2*j),i] = paste0(test_mse_mean_lkflag,"(",test_mse_std_lkflag,")")
  }
}

write.csv(test_table, paste0("tables/hcp/regions/",subject,"_test_region.csv"))

}

time_end = Sys.time()
```

```{r}
print(time_end-time_start)
```


